/** Homepage Client Results — Problem / Solution / Outcome format */
export const HOME_CLIENT_RESULTS = [
  {
    num: '01',
    metric: '8 months',
    industry: 'Manufacturing',
    label: 'crash-free operation',
    problem: 'Database crashes affecting 15 users on the shop floor.',
    solution: 'Split Access front-end/back-end and optimized multi-user queries.',
    outcome: 'Zero crashes in 8 months; reporting runs in seconds.',
    before: '5+ crashes/week',
    after: 'Zero in 8 months',
    accent: 'primary',
    href: '/case-studies/manufacturing-inventory-tracking',
  },
  {
    num: '02',
    metric: '720× faster',
    industry: 'Construction',
    label: 'weekly reporting',
    problem: 'Six hours every week pulling and formatting job-cost reports.',
    solution: 'Excel VBA automation with one-click report generation.',
    outcome: 'Weekly report runs in 30 seconds; team reclaimed a full workday.',
    before: '6 hrs manual',
    after: '30 sec automated',
    accent: 'secondary',
    href: '/case-studies/construction-automated-reporting',
  },
  {
    num: '03',
    metric: '500 hrs/yr',
    industry: 'Finance',
    label: 'returned to the team',
    problem: 'Manual daily data entry between Excel and legacy systems.',
    solution: 'Live SQL pipeline with automated Excel refresh.',
    outcome: '500 hours per year returned to analysis work.',
    before: 'Manual data entry',
    after: 'Live SQL pipeline',
    accent: 'primary',
    href: '/case-studies/financial-services-data-integration',
  },
];
